kind: Service
apiVersion: v1
metadata:
  name: flashcards-java
  labels:
    app: flashcards-java
spec:
  type: ClusterIP
  selector:
    app: flashcards-java
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flashcards-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashcards-java
  template:
    metadata:
      labels:
        app: flashcards-java
        version: v1
    spec:
      containers:
      - name: flashcards-java
        image: flashcards-java
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
