server.port=4000

spring.application.name=flashcards
spring.datasource.url=jdbc:sqlite:./flashcards.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=false
server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2

spring.mappings.show=true

# spring.sql.init.mode=always
spring.thymeleaf.cache=false

flyway.baselineOnMigrate=true
flyway.validateMigrationNaming=true

# enables a dump of routes see: http://localhost:8080/actuator/mappings
management.endpoints.web.exposure.include=mappings

# You can also use DEBUG for less verbose parameter logging
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG

tts-gapi-key-path=./second-self-314011-ad468e29abfa.json
audio.files.url-prefix=/audio
audio.files.directory=audio
